[build]
  command = "npm run build"

  publish = "dist"

[build.environment]
  NODE_VERSION = "18"


# API routes
[[redirects]]
  from = "/api/*"

  to = "/.netlify/functions/server"
  status = 200

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200